
package com.corporaciongpf.integration.soap.empleado.services.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "empl_ptt", targetNamespace = "http://www.corporaciongpf.com/integration/empleado/services/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
	com.corporaciongpf.integration.soap.empleado.v1.ObjectFactory.class,
	com.corporaciongpf.integration.soap.empleado.services.v1.ObjectFactory.class
})
public interface EmplPtt {


    /**
     * 
     * @param empleadoRequest
     * @return
     *     returns com.corporaciongpf.integration.empleado.services.v1.EmpleadoResponse
     */
    @WebMethod(action = "query")
    @WebResult(name = "EmpleadoResponse", targetNamespace = "http://www.corporaciongpf.com/integration/empleado/services/v1", partName = "EmpleadoResponse")
    public EmpleadoResponse query(
        @WebParam(name = "EmpleadoRequest", targetNamespace = "http://www.corporaciongpf.com/integration/empleado/services/v1", partName = "EmpleadoRequest")
        EmpleadoRequest empleadoRequest);

}
