
package com.corporaciongpf.integration.soap.empleado.services.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmpleadoService", targetNamespace = "http://www.corporaciongpf.com/integration/empleado/services/v1", wsdlLocation = "file:/C:/Users/kachicaizaz/Documents/EmpleadoWSDL/empleado.wsdl")
public class EmpleadoService
    extends Service
{

    private final static URL EMPLEADOSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLEADOSERVICE_EXCEPTION;
    private final static QName EMPLEADOSERVICE_QNAME = new QName("http://www.corporaciongpf.com/integration/empleado/services/v1", "EmpleadoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/kachicaizaz/Documents/EmpleadoWSDL/empleado.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLEADOSERVICE_WSDL_LOCATION = url;
        EMPLEADOSERVICE_EXCEPTION = e;
    }

    public EmpleadoService() {
        super(__getWsdlLocation(), EMPLEADOSERVICE_QNAME);
    }

    public EmpleadoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLEADOSERVICE_QNAME, features);
    }

    public EmpleadoService(URL wsdlLocation) {
        super(wsdlLocation, EMPLEADOSERVICE_QNAME);
    }

    public EmpleadoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLEADOSERVICE_QNAME, features);
    }

    public EmpleadoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmpleadoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmplPtt
     */
    @WebEndpoint(name = "empl_ptt")
    public EmplPtt getEmplPtt() {
        return super.getPort(new QName("http://www.corporaciongpf.com/integration/empleado/services/v1", "empl_ptt"), EmplPtt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmplPtt
     */
    @WebEndpoint(name = "empl_ptt")
    public EmplPtt getEmplPtt(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.corporaciongpf.com/integration/empleado/services/v1", "empl_ptt"), EmplPtt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLEADOSERVICE_EXCEPTION!= null) {
            throw EMPLEADOSERVICE_EXCEPTION;
        }
        return EMPLEADOSERVICE_WSDL_LOCATION;
    }

}
