
package com.serviciosweb.intCoperah.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.gpf.postg.pedidos.util.Constantes;
import com.serviciosweb.intCoperah.db.ConnectionFybeca;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioIntegracion_Transaccional", targetNamespace = "WS_Transaccional", wsdlLocation = "http://serviciosgpf_test.shiftlabor.com/WS_Transaccional/ServicioIntegracion_Transaccional.asmx?wsdl")
public class ServicioIntegracionTransaccional
    extends Service
{

    private final static URL SERVICIOINTEGRACIONTRANSACCIONAL_WSDL_LOCATION;
    private final static WebServiceException SERVICIOINTEGRACIONTRANSACCIONAL_EXCEPTION;
    private final static QName SERVICIOINTEGRACIONTRANSACCIONAL_QNAME = new QName("WS_Transaccional", "ServicioIntegracion_Transaccional");

    static {
        URL url = null;
        WebServiceException e = null;
		ConnectionFybeca CFy = new ConnectionFybeca();

        try {
        	String[] infoTransaccional = CFy.getDataWS();
    		System.out.println(infoTransaccional[3]);
            url = new URL(infoTransaccional[3]);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOINTEGRACIONTRANSACCIONAL_WSDL_LOCATION = url;
        SERVICIOINTEGRACIONTRANSACCIONAL_EXCEPTION = e;
    }

    public ServicioIntegracionTransaccional() {
        super(__getWsdlLocation(), SERVICIOINTEGRACIONTRANSACCIONAL_QNAME);
    }

    public ServicioIntegracionTransaccional(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOINTEGRACIONTRANSACCIONAL_QNAME, features);
    }

    public ServicioIntegracionTransaccional(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOINTEGRACIONTRANSACCIONAL_QNAME);
    }

    public ServicioIntegracionTransaccional(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOINTEGRACIONTRANSACCIONAL_QNAME, features);
    }

    public ServicioIntegracionTransaccional(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioIntegracionTransaccional(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioIntegracionTransaccionalSoap
     */
    @WebEndpoint(name = "ServicioIntegracion_TransaccionalSoap")
    public ServicioIntegracionTransaccionalSoap getServicioIntegracionTransaccionalSoap() {
        return super.getPort(new QName("WS_Transaccional", "ServicioIntegracion_TransaccionalSoap"), ServicioIntegracionTransaccionalSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioIntegracionTransaccionalSoap
     */
    @WebEndpoint(name = "ServicioIntegracion_TransaccionalSoap")
    public ServicioIntegracionTransaccionalSoap getServicioIntegracionTransaccionalSoap(WebServiceFeature... features) {
        return super.getPort(new QName("WS_Transaccional", "ServicioIntegracion_TransaccionalSoap"), ServicioIntegracionTransaccionalSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOINTEGRACIONTRANSACCIONAL_EXCEPTION!= null) {
            throw SERVICIOINTEGRACIONTRANSACCIONAL_EXCEPTION;
        }
        return SERVICIOINTEGRACIONTRANSACCIONAL_WSDL_LOCATION;
    }

}
