
package com.serviciosweb.intCoperah.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioIntegracion_TransaccionalSoap", targetNamespace = "WS_Transaccional")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioIntegracionTransaccionalSoap {


    /**
     * 
     * @param infoCarga
     * @return
     *     returns ws_transaccional.InfoRespuesta
     */
    @WebMethod(operationName = "Procesar", action = "WS_Transaccional/Procesar")
    @WebResult(name = "ProcesarResult", targetNamespace = "WS_Transaccional")
    @RequestWrapper(localName = "Procesar", targetNamespace = "WS_Transaccional", className = "ws_transaccional.Procesar")
    @ResponseWrapper(localName = "ProcesarResponse", targetNamespace = "WS_Transaccional", className = "ws_transaccional.ProcesarResponse")
    public InfoRespuesta procesar(
        @WebParam(name = "infoCarga", targetNamespace = "WS_Transaccional")
        InfoCarga infoCarga);

}
