--------------------------------------------------------
--  DDL for Table TB_FACTURA
--------------------------------------------------------

  CREATE TABLE "GINVOICE"."TB_FACTURA" 
   (	"ID" NUMBER(19,0), 
	"AGENCIA" VARCHAR2(20 BYTE), 
	"ARCHIVO" VARCHAR2(200 BYTE), 
	"ARCHIVO_LEGIBLE" VARCHAR2(200 BYTE), 
	"CLAVE_ACCESO" VARCHAR2(100 BYTE), 
	"CLAVE_INTERNA" VARCHAR2(100 BYTE), 
	"COD_DOC" VARCHAR2(100 BYTE), 
	"COD_PUNTO_EMISION" VARCHAR2(100 BYTE), 
	"COD_SECUENCIAL" VARCHAR2(100 BYTE), 
	"CONTRIBUYENTE_ESPECIAL" VARCHAR2(5 BYTE), 
	"CORREO_NOTIFICACION" VARCHAR2(300 BYTE), 
	"DIR_ESTABLECIMIENTO" VARCHAR2(300 BYTE), 
	"ESTADO" VARCHAR2(15 BYTE), 
	"FECHA_AUTORIZACION" DATE, 
	"FECHA_EMISION_BASE" DATE, 
	"GUIA_REMISION" VARCHAR2(100 BYTE), 
	"IDENTIFICACION_COMPRADOR" VARCHAR2(50 BYTE), 
	"IDENTIFICADOR_USUARIO" VARCHAR2(50 BYTE), 
	"IMPORTE_TOTAL" NUMBER(19,2), 
	"INFO_ADICIONAL" VARCHAR2(500 BYTE), 
	"MONEDA" VARCHAR2(50 BYTE), 
	"NUMERO_AUTORIZACION" VARCHAR2(200 BYTE), 
	"OBLIGADO_CONTABILIDAD" VARCHAR2(3 BYTE), 
	"OBSERVACION_CANCELACION" VARCHAR2(2000 BYTE), 
	"PROCESO" VARCHAR2(20 BYTE), 
	"PROPINA" NUMBER(19,2), 
	"PTO_EMISION" VARCHAR2(100 BYTE), 
	"RAZON_SOCIAL_COMPRADOR" VARCHAR2(300 BYTE), 
	"REQUIERE_CANCELACION" VARCHAR2(1 BYTE), 
	"RUC" VARCHAR2(13 BYTE), 
	"SEC_NOTA_CREDITO" VARCHAR2(100 BYTE), 
	"SEC_ORIGINAL" VARCHAR2(100 BYTE), 
	"TAREA" VARCHAR2(3 BYTE), 
	"TIPO_AMBIENTE" VARCHAR2(1 BYTE), 
	"TIPO_EJECUCION" VARCHAR2(3 BYTE), 
	"TIPO_EMISION" VARCHAR2(1 BYTE), 
	"TIPO_GENERACION" VARCHAR2(3 BYTE), 
	"TIPO_ID_COMPRADOR" VARCHAR2(50 BYTE), 
	"TOTAL_DESCUENTO" NUMBER(19,2), 
	"TOTAL_SIN_IMPUESTOS" NUMBER(19,2), 
	"ID_LOTE" NUMBER(19,0), 
	"FECHA_EMISION_TMP" VARCHAR2(10 BYTE), 
	"ORDEN_COMPRA" VARCHAR2(100 BYTE), 
	"MENSAJE_REIM" VARCHAR2(300 BYTE), 
	"FECHA_RECEP_MAIL" DATE, 
	"FECHA_LEC_TRAD" DATE, 
	"FECHA_ENT_REIM" DATE, 
	"ARCHIVO_GEN_REIM" VARCHAR2(255 BYTE), 
	"MODO_ENVIO" VARCHAR2(15 BYTE), 
	"BASE_CERO" NUMBER(19,2), 
	"BASE_DOCE" NUMBER(19,2), 
	"IVA" NUMBER(19,2), 
	"BASE_ICE" NUMBER(19,2), 
	"BASE_IRBP" NUMBER(19,2), 
	"ICE" NUMBER(19,2), 
	"IRBP" NUMBER(19,2), 
	"IS_OFERTON" VARCHAR2(4 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GINVOICE_PART" 
  PARTITION BY RANGE ("FECHA_EMISION_BASE") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) STORE IN ("GINVOICE_PART") 
 (PARTITION "P0"  VALUES LESS THAN (TO_DATE(' 2014-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GINVOICE_PART" ) 
  PARALLEL 4 ;
  GRANT SELECT ON "GINVOICE"."TB_FACTURA" TO "ADM";
  GRANT SELECT ON "GINVOICE"."TB_FACTURA" TO "GPFDBPR_GPFDB";
